export const projects = [
  {
    slug: "ria-money-transfer",
    title: "RIA Money Transfer",
    year: "2024",
    fullDate: "05/03/2024",
    image: "/1.avif",
    tags: ["Marketing", "Consulenza"],
    description: "Il nostro obiettivo è stato creare una strategia mirata per la community italiana, evidenziando un approccio innovativo al marketing digitale e offrendo un'esperienza intuitiva e coinvolgente per esplorare al meglio i loro servizi.",
    category: "Strategia Marketing",
    client: "RIA",
    services: "Strategia Marketing",
    section1Title: "Strategia Digitale e Branding",
    longDescription1: "Per RIA Money Transfer, abbiamo sviluppato una strategia di marketing 360°, curando la presenza online attraverso l'ottimizzazione SEO, la gestione dei canali social e la creazione di campagne pubblicitarie mirate. L'obiettivo era aumentare la visibilità del brand e rafforzarne la reputazione.",
    middleSectionTitle: "Marketing Offline e Campagne Promozionali",
    middleSectionText: "Abbiamo implementato strategie di marketing tradizionale, con campagne pubblicitarie offline, eventi promozionali e collaborazioni strategiche. L'integrazione tra marketing digitale e offline ha permesso a RIA Money Transfer di ampliare il proprio pubblico e consolidare il proprio posizionamento nel settore.",
    galleryImages: ["/1.avif", "/1.avif"]
  },
  {
    slug: "latin-barber-studio",
    title: "Latin Barber Studio",
    year: "2025",
    fullDate: "MAY 2025",
    image: "/latinbarber.avif",
    tags: ["SITO WEB", "SEO"],
    description: "Abbiamo sviluppato un sito web personalizzato integrando un sistema di prenotazione avanzato con ChatBot su WhatsApp. Inoltre, abbiamo implementato un CRM e un software di marketing per ottimizzare la gestione dei clienti e automatizzare le strategie di comunicazione.",
    category: "Barbershop",
    client: "Anonimo",
    showPerformance: true,
    galleryImages: ["/latinbarberb.webp", "/latinbarberc.avif"],
    services: "Web design & Web development",
    websiteUrl: "#",
    longDescription1: "Abbiamo sviluppato una pagina web con un design incredibile e moderno, curato nei minimi dettagli per garantire un'esperienza utente intuitiva, fluida e coinvolgente.",
    longDescription2: "Per LatinBarber Studio, abbiamo implementato una strategia SEO avanzata per migliorare il posizionamento online e aumentare la visibilità sui motori di ricerca. Attraverso l'ottimizzazione tecnica, la creazione di contenuti mirati e il miglioramento della local SEO, abbiamo rafforzato la presenza digitale del brand, rendendolo un punto di riferimento per chi cerca un barbiere a Milano.",
    section2Title: "Sistema di Prenotazione Avanzato con Intelligenza Artificiale e WhatsApp – MEDIACOM",
    section2Text: "Abbiamo implementato un sistema di prenotazione intelligente, parzialmente automatizzato, che integra calendario, notifiche automatiche e gestione degli appuntamenti direttamente su WhatsApp. Grazie all'integrazione con l'Intelligenza Artificiale, il sistema riduce drasticamente il tempo di risposta, aumenta le conversioni e migliora l'esperienza cliente."
  },
  {
    slug: "mi-lindo-ecuador",
    title: "Mi Lindo Ecuador",
    year: "2024",
    fullDate: "11 AGO 2024",
    image: "/3.avif",
    tags: ["EVENTI", "GESTIONE DEL PUBBLICO"],
    description: "Abbiamo curato ogni aspetto dell'organizzazione dell'evento Mi Lindo Ecuador, garantendo il successo del Festival latino più grande in Italia, che ha accolto oltre 35.000 partecipanti. Dalla strategia di comunicazione all'esecuzione del marketing sul campo, abbiamo curato i minimi dettagli logistici e promozionali, coordinando la sicurezza e il divertimento di questo evento unico nel suo genere.",
    category: "Human",
    client: "Anonimo",
    services: "Eventi",
    galleryImages: ["/3.avif", "/3.avif"],
    section1Title: "Strategia Digitale e Identità Visiva",
    longDescription1: "Abbiamo creato una strategia digitale completa per Mi Lindo Ecuador, sviluppando un sito web moderno e intuitivo, allineando con la UCD e curando la gestione branding dell'evento. Ogni dettaglio visivo è stato progettato per riflettere l'essenza culturale e festiva dell'Ecuador, garantendo una comunicazione chiara e coinvolgente.",
    longDescription2: "Ogni dettaglio video è stato progettato per riflettere l'essenza culturale e festiva dell'Ecuador, garantendo una comunicazione chiara e coinvolgente.",
    middleSectionTitle: "Organizzazione dell'Evento e Autorizzazioni",
    middleSectionText: "Dalla fase iniziale fino al giorno dell'evento, abbiamo gestito l'intera pianificazione e organizzazione, occupandoci dei permessi comunali, licenze e logistica. Abbiamo coordinato ogni aspetto amministrativo per garantire il rispetto delle normative e un evento senza imprevisti.",
    section2Title: "Sicurezza, Artisti e Gestione sul Campo",
    section2Text: "Abbiamo lavorato sulla gestione della sicurezza con guardie e steward e misure per tutti i partecipanti. Inoltre, ci siamo occupati della selezione e coordinamento degli artisti, del personale e di tutti i collaboratori, assicurando un'organizzazione impeccabile e un intrattenimento straordinario."
  },
  {
    slug: "creacos-srl",
    title: "Creacos SRL",
    year: "2023",
    fullDate: "15/05/2023",
    image: "/4.avif",
    tags: ["Marketing", "Sito web"],
    description: "Il nostro obiettivo è stato creare una strategia mirata per la community italiana, evidenziando un approccio innovativo al marketing digitale e offrendo un'esperienza intuitiva e coinvolgente per esplorare al meglio i loro servizi.",
    category: "Construction",
    client: "CREACOS SRL",
    services: "Strategia Marketing 360",
    section1Title: "SEO",
    longDescription1: "Performance e Responsiveness sono stati al centro del nostro lavoro. Abbiamo ottimizzato ogni aspetto del sito per garantire velocità e accessibilità da qualsiasi dispositivo.",
    galleryImages: ["/4.avif", "/4.avif"]
  }
]
